//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainManagementMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tbl_Clients
    {
       
        public int ClientId { get; set; }
        [Display(Name = "Client / Company Name")]
        [Required (ErrorMessage ="Please Enter Client / Company Name.")]
        public string ClientName { get; set; }
        [Display(Name = "Contact Person Name")]
        public string ContactPersonName { get; set; }
        [Display(Name = "Mobile Numbar")]
        [Required(ErrorMessage ="Please Enter Mobile Number.")]
        public string MobileNumbar { get; set; }
        [Display(Name ="Email-Id")]
        [Required(ErrorMessage ="Please Enter Email Id.")]
        public string EmailId { get; set; }
       [Required (ErrorMessage ="Please Enter Address")]
        public string Address { get; set; }
        [Required(ErrorMessage ="Please Select")]
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    }
}
